# https://github.com/lowlighter/metrics/blob/master/source/plugins/habits/README.md

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: "0 4 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Midly interesting facts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: Europe/Berlin

