#

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: "0 4 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Opened by user
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.followup.user.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: user

