#

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: "0 4 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          #plugin_languages_ignored: >-
          #  html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
          #  gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4

